[tool.bumpversion]
current_version = "0.1.2"
commit = false
tag = false
message = "Bump version: {current_version} â†’ {new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "src/makefolio/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = '## [Unreleased]'
replace = '## [Unreleased]\n\n## [{new_version}] - {utcnow:%Y-%m-%d}'

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = '[Unreleased]: https://github.com/martian56/makefolio/compare/v{current_version}...HEAD'
replace = '[Unreleased]: https://github.com/martian56/makefolio/compare/v{new_version}...HEAD\n[{new_version}]: https://github.com/martian56/makefolio/releases/tag/v{new_version}'

